http:
  routers:
    all-models:
      rule: "Path(`/v1/models`)"
      service: all-models
      entryPoints:
        - llama-servers

  services:
    all-models:
      loadBalancer:
        servers:
          - url: "http://all-models:9080"
