http:
  routers:
    llama-server-2:
      rule: "HeaderRegexp(`Authorization`, `^Bearer (API_KEY-2)$`)"
      service: llama-server-2
      entryPoints:
        - llama-servers

  services:
    llama-server-2:
      loadBalancer:
        servers:
          - url: "http://llama-server-2:8012"
