http:
  routers:
    llama-server-1:
      rule: "HeaderRegexp(`Authorization`, `^Bearer (API_KEY-1)$`)"
      service: llama-server-1
      entryPoints:
        - llama-servers
    llama-server-2:
      rule: "HeaderRegexp(`Authorization`, `^Bearer (API_KEY-2)$`)"
      service: llama-server-2
      entryPoints:
        - llama-servers

  services:
    llama-server-1:
      loadBalancer:
        servers:
          - url: "http://llama-server-1:8011"
    llama-server-2:
      loadBalancer:
        servers:
          - url: "http://llama-server-2:8012"
